"""empty message

Revision ID: 229106c9f115
Revises: 
Create Date: 2021-08-24 22:44:19.532529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229106c9f115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('especialidade', sa.String(length=40), nullable=False),
    sa.Column('cpf', sa.String(length=40), nullable=False),
    sa.Column('crm', sa.Integer(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('senha_hash', sa.LargeBinary(length=128), nullable=False),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('cpf', sa.String(length=40), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('senha_hash', sa.LargeBinary(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consulta')
    op.drop_table('paciente')
    op.drop_table('medico')
    # ### end Alembic commands ###
