"""empty message

Revision ID: d81b0f604fa8
Revises: 
Create Date: 2021-08-10 13:45:26.412996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81b0f604fa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('especialidade', sa.String(length=40), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('crm', sa.Integer(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('senha_hash', sa.LargeBinary(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('senha_hash', sa.LargeBinary(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paciente')
    op.drop_table('medico')
    # ### end Alembic commands ###
