"""empty message

Revision ID: f50ca6264dfd
Revises: 
Create Date: 2021-07-28 22:07:45.204091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50ca6264dfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('especialidade', sa.String(length=40), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('crm', sa.Integer(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('senha_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medico')
    # ### end Alembic commands ###
